### ISSUE TITLE
CLI tool is still not respecting user preferences for telemetry

### ISSUE THREAD

**Issue by bruteforks** [apptension/saas-boilerplate#591] opened 2024-07-03 19:15 UTC
### Describe the bug

https://github.com/apptension/saas-boilerplate/issues/587

### Steps to reproduce

pull fix, pnpm i -w, retest if telemetry is being sent

### System Info

```shell
all systems
```

### Logs

Please leave open until fixed, or maybe disable telemetry until this is able to be addressed? Like I said in the other issue, this also affects your create-saas-boilerplate repo

### Validations

- [X] Follow our [Code of Conduct](https://github.com/apptension/saas-boilerplate/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/apptension/saas-boilerplate/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://docs.demo.saas.apptoku.com/).
- [X] Check that there isn't [already an issue](https://github.com/apptension/saas-boilerplate/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/apptension/saas-boilerplate/discussions) or join our [Discord Chat Server](https://discord.apptension.com).

**Comment by mkleszcz** [comment] 2024-07-05 14:40
Closing as I'm not able to reproduce this issue and there is no additional information how to do this. Also this is a duplicate of an previous issue.

**Closed by mkleszcz** 2024-07-05 14:40 UTC
